# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://zones.arilyn.cc
timezone: Africa/Cairo

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: r2cook # the main title

tagline: Red Teaming | CTFs | OSCP Journey # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  Cybersecurity blog by r2cook featuring CTF writeups, red teaming notes, OSCP preparation, and penetration testing research.

url: "https://r2cook.github.io"

github:
  username: r2cook

twitter:
  username: 0xr2cook

social:
  name: r2cook
  email: r2cook@gmail.com
  fediverse_handle:
  links:
    - https://twitter.com/0xr2cook
    - https://github.com/r2cook

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id: G-CQHH3DZ94X
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode: dark

cdn:

avatar: /assets/img/logo.png

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - vendor
  - assets/robots.txt
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .jekyll-cache
  - .jekyll-metadata

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

html-proofer:
  check_external_hash: false
  enforce_https: false